apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.name }}
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "32Mi"
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.container.acr }}/{{ .Values.container.image }}:{{ .Values.container.tag }}
          readinessProbe:
            httpGet:
              path: {{ .Values.container.probeurl }}
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
status: {}
